logging:
  level:
    io:
      seata: debug
server:
  port: 9091
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
        username: nacos
        password: nacos
        namespace: baeba154-3521-468d-b5de-8efb86cbf3d9
        # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
        group: SEATA_GROUP

  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3307/seata_order?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&characterSetResults=utf8&useSSL=true&allowMultiQueries=true
      username: root
seata:
  application-id: ${spring.application.name}
  # 这里的配置对应 seataServer.properties 中的 service.vgroupMapping.order-service-group=default
  tx-service-group: order-service-group
  # 使用 druid  代理报错！
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8849
      username: nacos
      password: nacos
      namespace: baeba154-3521-468d-b5de-8efb86cbf3d9
      # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
      group: SEATA_GROUP
      dataId: "seataServer.properties"
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8849
      username: nacos
      password: nacos
      namespace: baeba154-3521-468d-b5de-8efb86cbf3d9
      # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
      group: SEATA_GROUP

