logging:
  level:
    io:
      seata: debug
server:
  port: 9092
spring:
  application:
    name: storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
        username: nacos
        password: nacos
        namespace: baeba154-3521-468d-b5de-8efb86cbf3d9
        group: SEATA_GROUP
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3307/seata_storage?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&characterSetResults=utf8&useSSL=true&allowMultiQueries=true
      username: root

seata:
  application-id: ${spring.application.name}
  tx-service-group: storage-service-group
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8849
      username: nacos
      password: nacos
      namespace: baeba154-3521-468d-b5de-8efb86cbf3d9
      # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
      group: SEATA_GROUP
      dataId: "seataServer.properties"
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8849
      username: nacos
      password: nacos
      namespace: baeba154-3521-468d-b5de-8efb86cbf3d9
      # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
      group: SEATA_GROUP
